# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Ubuntu 12.04"
  config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box'

  config.vm.network "private_network", ip: "192.168.33.10"
  config.ssh.forward_agent = true

  # Must have nfsd support, mac has this, but on Ubuntu just run:
  # apt-get install nfs-kernel-server portmap
  config.vm.synced_folder "../drupal", "/var/www/drupal", type: 'nfs'

   config.vm.provider "virtualbox" do |vb|
     vb.name = 'DrupalBox'
   end

   # config.vm.provision = 'puppet'
   config.vm.provision "puppet" do |puppet|
     puppet.module_path = "modules"
   end
end
